---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: https://stg-api.stackbit.com/project/603df22328e38d00163463df/webhook/forestry
sections:
- type: document
  path: config.yaml
  label: Site Configuration
  templates:
  - config
- type: directory
  path: data/authors
  label: Person
  create: all
  match: "**/*"
  new_doc_ext: yaml
  templates:
  - person
- type: document
  path: content/blog/_index.md
  label: Blog
  templates:
  - blog
- type: directory
  path: content
  label: Pages
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - landing
  - page
  - post
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.80.0
